### ISSUE TITLE
Plugin Structure and WordPress Coding Standards

### ISSUE THREAD

**Issue by aaronware** [onelogin/wordpress-saml#108]
@pitbulk are you open to other pull requests? I see a few other tasks related to making the plugin compatible with composer/wpackagist. I could also help with automating deployment to wordpress.org using GitHub actions, sweep for WordPress coding standard, code organization, etc.

**Comment by aaronware** [comment]
Obivously, one of the bigger items to tackle is the plugin structure and moving things around if you wanted to support wpackagist (which is something we'd love to utilize and help implement). I didn't want to step on your toes if you're doing things. But there are some things at @linchpin we'd want to do to help if you and @onelogin are open to it.

**Comment by pitbulk** [comment]
Sure, I'm always open to contribution.

The plugin is not following WP coding standard because I maintain SAML toolkits for PHP, Python, Ruby and Java as well as plugins for other open source solutions, so at the end for me is almost impossible to write each toolkit/plugin with the perfect syntax.  But if you take the time to apply the formats as well as help with the development cycle, perfect.

**Comment by pitbulk** [comment]
btw I'm releasing a new version with the fix (3.3.1) and your proposal could go in a future 3.4.0 version
Adopt composer in order to handle dependencies like php-saml would be great

**Comment by aaronware** [comment]
Sounds good to me. I'm going to close this out and make issues in the linchpin/wordpress-saml fork.  I know that @nate-allen from our side also had some ideas regarding some filters that would be really useful as well.
