### ISSUE TITLE
2.4.2 got Reference validation failed error

### ISSUE THREAD

**Issue by tuanmh** [onelogin/wordpress-saml#22]
Hi guys, thank you again for this plugin. We've just upgraded to 2.4.2 and got this error: `Reference validation failed` in `xmlseclibs.php` line `923`. I reverted it back to 2.4.1 and it works perfectly. Could you please help? Looks like it has something to do with this commit:

https://github.com/onelogin/php-saml/commit/39878dd041bc7fa91f19e9c04ef4e4008e3079cc

**Comment by pitbulk** [comment]
Hi @tuanmh

Can you provide the SAMLResponse that is failing?

**Comment by tuanmh** [comment]
> f no exception is raised, then the problem is not related with the new processSignedElements and could be related with the _queryAssertion and the _decryptAssertion since xmlseclibs was not modified, but is wrong since unit test past and I also made tests with different scenarios.

Yes, there was no exception at that break point. I'll send the SAMLResponse to the email at your github account.

**Comment by tuanmh** [comment]
Hi @pitbulk, do you have any updates on this?

**Comment by pitbulk** [comment]
No sorry, I will spend some time today

**Comment by pitbulk** [comment]
Your SAMLResponse contains a Signature with a KeyInfo that contains X509IssuerSerial element instead of X509Certificate.

From  2.4.1 to  2.4.2, there was a change with the php-saml library (from 2.8.0 to 2.9.0) but [nothing that changed](https://github.com/onelogin/php-saml/compare/v2.8.0...master) the xmlseclibs file, so I don't know how is possible that your SAMLResponse works on 2.4.1 and not at 2.4.1

**Comment by pitbulk** [comment]
I replied you by mail.

**Comment by tuanmh** [comment]
hey @pitbulk: do you have time to have a look at this issue? or you can give me some instructions so I'll do it. This is important for us to get moving and updated with latest version to prevent any security risks. Thank you again!

**Comment by pitbulk** [comment]
I had no progress on that. Can you generate temp certificate/private key at
https://www.samltool.com/self_signed_certs.php
replace on your SP settings the real certs but those new (remember also to change the ADFS settings with this new SP public cert).

 Then try if the SAMLResponse also is rejected due "Reference validation failed error" and in this is the case, send to me by mail:
- the base64 encoded saml response (I want it encoded in order to avoid any manipulation).
- the self-signed private key and cert used.
So I will be able to reproduce what happening.

**Comment by tuanmh** [comment]
Just an update on this @pitbulk, we've upgraded our staging environment to 2.4.4 and everything is working fine - so there must be some different between the 2 versions (2.4.2 and 2.4.4) - I'm not too sure for now though.

**Comment by pitbulk** [comment]
yes 2.4.4 uses the latest php-saml toolkit, use it.
